const records = [
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 87,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
    {
        timeStamp: '13th Jan 7:30pm',
        current: 33,
        chargerInputVoltage: 33,
        chargerOutputVoltage: 89,
        BatteryOutputVoltage: 38,
        chargerOutputCurrent: 67,
    },
];
export { records };
